parameters: #List of Parameters that user can send in requests
  account_address:
    regex: ^[0-9a-zA-Z:]{42,100}$
    type: string
  account_username:
    # regex: ^(?=.{3,20}$)(?![_])(?!.*[_]{2})[a-zA-Z0-9_]+(?<![_])$
    regex: ^(?=.{4,25}$)(?![_])(?!.*[_]{2})[a-zA-Z][a-zA-Z0-9_]+(?![_])$
    type: string
  account_email:
    regex: ^(?=.{6,100}$)(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])
    type: string
  collection_id:
    regex: ^[0-9a-zA-Z]{32,32}$
    type: string
  collection_nsfw:
    type: boolean
  nft_id:
    regex: ^[0-9a-zA-Z]{32,32}$
    type: string
  nft_nsfw:
    type: boolean
  nft_minted:
    type: boolean
  nft_launched:
    type: boolean
  nft_listed:
    type: boolean
  